In [1]:
import pandas as pd
import numpy as np
import nltk
import re

In [2]:
dataset=pd.read_csv('train.csv')

In [3]:
dataset.head()

                                            Question  label
0  A solitaire game is played as follows.  Six di...      3
1  2. The school table tennis championship was he...      5
2  Given that $x, y,$ and $z$ are real numbers th...      0
3  $25 \cdot 22$ Given three distinct points $P\l...      1
4  I am thinking of a five-digit number composed ...      5

In [4]:
from nltk.tokenize import sent_tokenize

In [5]:
question_set=dataset['Question']

In [6]:
text=str(question_set[0])

In [7]:
dataset_1=dataset.copy()

In [8]:
dataset_1['transformed_1']=dataset_1['Question']

In [9]:
nltk.sent_tokenize(dataset_1['transformed_1'][0])

['A solitaire game is played as follows.',
 'Six distinct pairs of matched tiles are placed in a bag.',
 "The player randomly draws tiles one at a time from the bag and retains them, except that matching tiles are put aside as soon as they appear in the player's hand.",
 'The game ends if the player ever holds three tiles, no two of which match; otherwise the drawing continues until the bag is empty.',
 'The probability that the bag will be emptied is $p/q,\\,$ where $p\\,$ and $q\\,$ are relatively prime positive integers.',
 'Find $p+q.\\,$']

In [10]:
dataset_1['transformed_2'] = dataset_1['transformed_1'].apply(lambda x: re.sub(r'[^\w\s]', '', x))

In [11]:
dataset_1

,Question,label,transformed_1,transformed_2
0,A solitaire game is played as follows. Six di...,3,A solitaire game is played as follows. Six di...,A solitaire game is played as follows Six dis...
1,2. The school table tennis championship was he...,5,2. The school table tennis championship was he...,2 The school table tennis championship was hel...
2,"Given that $x, y,$ and $z$ are real numbers th...",0,"Given that $x, y,$ and $z$ are real numbers th...",Given that x y and z are real numbers that sat...
3,$25 \cdot 22$ Given three distinct points $P\l...,1,$25 \cdot 22$ Given three distinct points $P\l...,25 cdot 22 Given three distinct points Pleftx_...
4,I am thinking of a five-digit number composed ...,5,I am thinking of a five-digit number composed ...,I am thinking of a fivedigit number composed o...
...,...,...,...,...
10184,Is there a first- or second-degree polynomial ...,0,Is there a first- or second-degree polynomial ...,Is there a first or seconddegree polynomial th...
10185,4. Let the side lengths of $\triangle A B C$ b...,1,4. Let the side lengths of $\triangle A B C$ b...,4 Let the side lengths of triangle A B C be 6 ...
10186,A triangular array of squares has one square i...,5,A triangular array of squares has one square i...,A triangular array of squares has one square i...
10187,Suppose we are given seven points that are equ...,1,Suppose we are given seven points that are equ...,Suppose we are given seven points that are equ...
10188,"4. In a football tournament, only teams from S...",5,"4. In a football tournament, only teams from S...",4 In a football tournament only teams from Sma...

In [12]:
dataset_1['s_tokens'] = dataset_1['transformed_2'].apply(sent_tokenize)

In [13]:
dataset_2=dataset_1.drop(['transformed_1','transformed_2'],axis=1)

In [14]:
dataset_2

,Question,label,s_tokens
0,A solitaire game is played as follows. Six di...,3,[A solitaire game is played as follows Six di...
1,2. The school table tennis championship was he...,5,[2 The school table tennis championship was he...
2,"Given that $x, y,$ and $z$ are real numbers th...",0,[Given that x y and z are real numbers that sa...
3,$25 \cdot 22$ Given three distinct points $P\l...,1,[25 cdot 22 Given three distinct points Pleftx...
4,I am thinking of a five-digit number composed ...,5,[I am thinking of a fivedigit number composed ...
...,...,...,...
10184,Is there a first- or second-degree polynomial ...,0,[Is there a first or seconddegree polynomial t...
10185,4. Let the side lengths of $\triangle A B C$ b...,1,[4 Let the side lengths of triangle A B C be 6...
10186,A triangular array of squares has one square i...,5,[A triangular array of squares has one square ...
10187,Suppose we are given seven points that are equ...,1,[Suppose we are given seven points that are eq...
10188,"4. In a football tournament, only teams from S...",5,[4 In a football tournament only teams from Sm...

In [15]:
from nltk.tokenize import word_tokenize
dataset_2['w_tokens'] = dataset_2['Question'].apply(word_tokenize)

In [16]:
dataset_2

,Question,label,s_tokens,w_tokens
0,A solitaire game is played as follows. Six di...,3,[A solitaire game is played as follows Six di...,"[A, solitaire, game, is, played, as, follows, ..."
1,2. The school table tennis championship was he...,5,[2 The school table tennis championship was he...,"[2, ., The, school, table, tennis, championshi..."
2,"Given that $x, y,$ and $z$ are real numbers th...",0,[Given that x y and z are real numbers that sa...,"[Given, that, $, x, ,, y, ,, $, and, $, z, $, ..."
3,$25 \cdot 22$ Given three distinct points $P\l...,1,[25 cdot 22 Given three distinct points Pleftx...,"[$, 25, \cdot, 22, $, Given, three, distinct, ..."
4,I am thinking of a five-digit number composed ...,5,[I am thinking of a fivedigit number composed ...,"[I, am, thinking, of, a, five-digit, number, c..."
...,...,...,...,...
10184,Is there a first- or second-degree polynomial ...,0,[Is there a first or seconddegree polynomial t...,"[Is, there, a, first-, or, second-degree, poly..."
10185,4. Let the side lengths of $\triangle A B C$ b...,1,[4 Let the side lengths of triangle A B C be 6...,"[4, ., Let, the, side, lengths, of, $, \triang..."
10186,A triangular array of squares has one square i...,5,[A triangular array of squares has one square ...,"[A, triangular, array, of, squares, has, one, ..."
10187,Suppose we are given seven points that are equ...,1,[Suppose we are given seven points that are eq...,"[Suppose, we, are, given, seven, points, that,..."
10188,"4. In a football tournament, only teams from S...",5,[4 In a football tournament only teams from Sm...,"[4, ., In, a, football, tournament, ,, only, t..."

In [18]:
dataset_2

,Question,label,s_tokens,w_tokens
0,A solitaire game is played as follows. Six di...,3,[A solitaire game is played as follows Six di...,"[A, solitaire, game, is, played, as, follows, ..."
1,2. The school table tennis championship was he...,5,[2 The school table tennis championship was he...,"[2, ., The, school, table, tennis, championshi..."
2,"Given that $x, y,$ and $z$ are real numbers th...",0,[Given that x y and z are real numbers that sa...,"[Given, that, $, x, ,, y, ,, $, and, $, z, $, ..."
3,$25 \cdot 22$ Given three distinct points $P\l...,1,[25 cdot 22 Given three distinct points Pleftx...,"[$, 25, \cdot, 22, $, Given, three, distinct, ..."
4,I am thinking of a five-digit number composed ...,5,[I am thinking of a fivedigit number composed ...,"[I, am, thinking, of, a, five-digit, number, c..."
...,...,...,...,...
10184,Is there a first- or second-degree polynomial ...,0,[Is there a first or seconddegree polynomial t...,"[Is, there, a, first-, or, second-degree, poly..."
10185,4. Let the side lengths of $\triangle A B C$ b...,1,[4 Let the side lengths of triangle A B C be 6...,"[4, ., Let, the, side, lengths, of, $, \triang..."
10186,A triangular array of squares has one square i...,5,[A triangular array of squares has one square ...,"[A, triangular, array, of, squares, has, one, ..."
10187,Suppose we are given seven points that are equ...,1,[Suppose we are given seven points that are eq...,"[Suppose, we, are, given, seven, points, that,..."
10188,"4. In a football tournament, only teams from S...",5,[4 In a football tournament only teams from Sm...,"[4, ., In, a, football, tournament, ,, only, t..."

In [ ]:
from nltk.tokenize import word_tokenize
dataset_2['w_tokens'] = dataset_2['Question'].apply(word_tokenize)

In [21]:
from nltk.stem import WordNetLemmatizer
lema=WordNetLemmatizer()
dataset_2['L_trans'] = dataset_2['w_tokens'].apply(lambda words: [lema.lemmatize(word) for word in words])

In [22]:
dataset_2

,Question,label,s_tokens,w_tokens,L_trans
0,A solitaire game is played as follows. Six di...,3,[A solitaire game is played as follows Six di...,"[A, solitaire, game, is, played, as, follows, ...","[A, solitaire, game, is, played, a, follows, ...."
1,2. The school table tennis championship was he...,5,[2 The school table tennis championship was he...,"[2, ., The, school, table, tennis, championshi...","[2, ., The, school, table, tennis, championshi..."
2,"Given that $x, y,$ and $z$ are real numbers th...",0,[Given that x y and z are real numbers that sa...,"[Given, that, $, x, ,, y, ,, $, and, $, z, $, ...","[Given, that, $, x, ,, y, ,, $, and, $, z, $, ..."
3,$25 \cdot 22$ Given three distinct points $P\l...,1,[25 cdot 22 Given three distinct points Pleftx...,"[$, 25, \cdot, 22, $, Given, three, distinct, ...","[$, 25, \cdot, 22, $, Given, three, distinct, ..."
4,I am thinking of a five-digit number composed ...,5,[I am thinking of a fivedigit number composed ...,"[I, am, thinking, of, a, five-digit, number, c...","[I, am, thinking, of, a, five-digit, number, c..."
...,...,...,...,...,...
10184,Is there a first- or second-degree polynomial ...,0,[Is there a first or seconddegree polynomial t...,"[Is, there, a, first-, or, second-degree, poly...","[Is, there, a, first-, or, second-degree, poly..."
10185,4. Let the side lengths of $\triangle A B C$ b...,1,[4 Let the side lengths of triangle A B C be 6...,"[4, ., Let, the, side, lengths, of, $, \triang...","[4, ., Let, the, side, length, of, $, \triangl..."
10186,A triangular array of squares has one square i...,5,[A triangular array of squares has one square ...,"[A, triangular, array, of, squares, has, one, ...","[A, triangular, array, of, square, ha, one, sq..."
10187,Suppose we are given seven points that are equ...,1,[Suppose we are given seven points that are eq...,"[Suppose, we, are, given, seven, points, that,...","[Suppose, we, are, given, seven, point, that, ..."
10188,"4. In a football tournament, only teams from S...",5,[4 In a football tournament only teams from Sm...,"[4, ., In, a, football, tournament, ,, only, t...","[4, ., In, a, football, tournament, ,, only, t..."

In [23]:
from nltk.corpus import stopwords
stop = set(stopwords.words('english'))
dataset_2['st_trans'] = dataset_2['L_trans'].apply(lambda x: [word for word in x if word.lower() not in stop])

In [24]:
dataset_2.head()

,Question,label,s_tokens,w_tokens,L_trans,st_trans
0,A solitaire game is played as follows. Six di...,3,[A solitaire game is played as follows Six di...,"[A, solitaire, game, is, played, as, follows, ...","[A, solitaire, game, is, played, a, follows, ....","[solitaire, game, played, follows, ., Six, dis..."
1,2. The school table tennis championship was he...,5,[2 The school table tennis championship was he...,"[2, ., The, school, table, tennis, championshi...","[2, ., The, school, table, tennis, championshi...","[2, ., school, table, tennis, championship, wa..."
2,"Given that $x, y,$ and $z$ are real numbers th...",0,[Given that x y and z are real numbers that sa...,"[Given, that, $, x, ,, y, ,, $, and, $, z, $, ...","[Given, that, $, x, ,, y, ,, $, and, $, z, $, ...","[Given, $, x, ,, ,, $, $, z, $, real, number, ..."
3,$25 \cdot 22$ Given three distinct points $P\l...,1,[25 cdot 22 Given three distinct points Pleftx...,"[$, 25, \cdot, 22, $, Given, three, distinct, ...","[$, 25, \cdot, 22, $, Given, three, distinct, ...","[$, 25, \cdot, 22, $, Given, three, distinct, ..."
4,I am thinking of a five-digit number composed ...,5,[I am thinking of a fivedigit number composed ...,"[I, am, thinking, of, a, five-digit, number, c...","[I, am, thinking, of, a, five-digit, number, c...","[thinking, five-digit, number, composed, even,..."

In [44]:
dataset_3=dataset_2.iloc[:,[0,1,-1]]

In [45]:
dataset_3

,Question,label,st_trans
0,A solitaire game is played as follows. Six di...,3,"[solitaire, game, played, follows, ., Six, dis..."
1,2. The school table tennis championship was he...,5,"[2, ., school, table, tennis, championship, wa..."
2,"Given that $x, y,$ and $z$ are real numbers th...",0,"[Given, $, x, ,, ,, $, $, z, $, real, number, ..."
3,$25 \cdot 22$ Given three distinct points $P\l...,1,"[$, 25, \cdot, 22, $, Given, three, distinct, ..."
4,I am thinking of a five-digit number composed ...,5,"[thinking, five-digit, number, composed, even,..."
...,...,...,...
10184,Is there a first- or second-degree polynomial ...,0,"[first-, second-degree, polynomial, take, valu..."
10185,4. Let the side lengths of $\triangle A B C$ b...,1,"[4, ., Let, side, length, $, \triangle, B, C, ..."
10186,A triangular array of squares has one square i...,5,"[triangular, array, square, ha, one, square, f..."
10187,Suppose we are given seven points that are equ...,1,"[Suppose, given, seven, point, equally, spaced..."
10188,"4. In a football tournament, only teams from S...",5,"[4, ., football, tournament, ,, team, Small, T..."

In [49]:
from nltk import pos_tag , ne_chunk
nltk.download('averaged_perceptron_tagger')
dataset_3['pos_tags'] = dataset_3['st_trans'].apply(lambda words: pos_tag(words))

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\saman\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
C:\Users\saman\AppData\Local\Temp\ipykernel_6704\2353725283.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_3['pos_tags'] = dataset_3['st_trans'].apply(lambda words: pos_tag(words))

In [50]:
dataset_3.head()

,Question,label,st_trans,pos_tags
0,A solitaire game is played as follows. Six di...,3,"[solitaire, game, played, follows, ., Six, dis...","[(solitaire, NN), (game, NN), (played, VBD), (..."
1,2. The school table tennis championship was he...,5,"[2, ., school, table, tennis, championship, wa...","[(2, CD), (., .), (school, NN), (table, JJ), (..."
2,"Given that $x, y,$ and $z$ are real numbers th...",0,"[Given, $, x, ,, ,, $, $, z, $, real, number, ...","[(Given, VBN), ($, $), (x, CD), (,, ,), (,, ,)..."
3,$25 \cdot 22$ Given three distinct points $P\l...,1,"[$, 25, \cdot, 22, $, Given, three, distinct, ...","[($, $), (25, CD), (\cdot, NNP), (22, CD), ($,..."
4,I am thinking of a five-digit number composed ...,5,"[thinking, five-digit, number, composed, even,...","[(thinking, VBG), (five-digit, JJ), (number, N..."

In [ ]:
'''
def extract_entities(word_list):
    text = ' '.join(word_list)
    tokens = word_tokenize(text)
    tagged = pos_tag(tokens)
    tree = ne_chunk(tagged)
    entities = []
    for subtree in tree:
        if isinstance(subtree, nltk.Tree):
            entity = ' '.join([word for word, tag in subtree])
            label = subtree.label()
            entities.append((entity, label))
    return entities

dataset_3['named_entities'] = dataset_3['st_trans'].apply(extract_entities)

'''

In [ ]:
dataset_3.head()